# Generated by Django 3.2.8 on 2021-11-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20211112_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='action',
        ),
    ]
