# Generated by Django 3.2.8 on 2021-11-12 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0003_remove_transaction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletaction',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='walletaction',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
