# Generated by Django 3.2.8 on 2021-11-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20211112_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletaction',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='walletaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='walletaction',
            name='object_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='Bid made to Afraha', max_length=255),
        ),
        migrations.AddField(
            model_name='walletaction',
            name='credit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='walletaction',
            name='action',
            field=models.CharField(choices=[('W', 'Withdraw'), ('D', 'Deposit'), ('B', 'Bid'), ('S', 'Subscription')], max_length=2, primary_key=True, serialize=False),
        ),
    ]
