# Generated by Django 3.2.8 on 2021-10-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_auto_20211016_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_price',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='rejected',
        ),
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
