# Generated by Django 3.2.8 on 2021-11-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_auto_20211023_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
